const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_GOOGLE_REQUEST = 'LOGIN_GOOGLE_REQUEST';
const LOGOUT = 'LOGOUT';

export const authTypes = {
    LOGIN_REQUEST,
  LOGIN_GOOGLE_REQUEST,
  LOGOUT
};
