const LOGIN_REQUEST = "LOGIN_REQUEST";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_GOOGLE_REQUEST = "LOGIN_GOOGLE_REQUEST";
const LOGIN_GOOGLE_SUCCESS = "LOGIN_GOOGLE_SUCCESS";
const LOGOUT = "LOGOUT";

export const authTypes = {
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_GOOGLE_REQUEST,
  LOGIN_GOOGLE_SUCCESS,
  LOGOUT,
};
