const LOGIN_REQUEST = "LOGIN_REQUEST";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_GOOGLE_REQUEST = "LOGIN_GOOGLE_REQUEST";
const LOGIN_GOOGLE_SUCCESS = "LOGIN_GOOGLE_SUCCESS";
const LOGOUT_REQUEST = "LOGOUT_REQUEST";
const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
const GET_LIST_ROLES_SUCCESS = "GET_LIST_ROLES_SUCCESS";
const GET_LIST_ROLES_REQUEST = "GET_LIST_ROLES_REQUEST";

export const authTypes = {
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_GOOGLE_REQUEST,
  LOGIN_GOOGLE_SUCCESS,
  LOGOUT_REQUEST,
  LOGOUT_SUCCESS,
  GET_LIST_ROLES_SUCCESS,
  GET_LIST_ROLES_REQUEST
};
