const DELETE_BUS_ROUTE_SUCCESS = 'DELETE_BUS_ROUTE_SUCCESS';
const DELETE_BUS_ROUTE_REQUEST = 'DELETE_BUS_ROUTE_REQUEST';
const GET_LIST_BUS_ROUTES_SUCCESS = 'GET_LIST_BUS_ROUTES_SUCCESS';
const GET_LIST_BUS_ROUTES_REQUEST = 'GET_LIST_BUS_ROUTES_REQUEST';
const ADD_BUS_ROUTE_REQUEST = 'ADD_BUS_ROUTE_REQUEST';
const ADD_BUS_ROUTE_SUCCESS = 'ADD_BUS_ROUTE_SUCCESS';
const UPDATE_BUS_ROUTE_REQUEST = 'UPDATE_BUS_ROUTE_REQUEST';
const UPDATE_BUS_ROUTE_SUCCESS = 'UPDATE_BUS_ROUTE_SUCCESS';
const SET_ACTIVE_BUS_ROUTE = 'SET_ACTIVE_BUS_ROUTE';
const CLEAR_ACTIVE_BUS_ROUTE = 'CLEAR_ACTIVE_BUS_ROUTE';

export const busRoutesTypes = {
  DELETE_BUS_ROUTE_SUCCESS,
  DELETE_BUS_ROUTE_REQUEST,
  GET_LIST_BUS_ROUTES_SUCCESS,
  GET_LIST_BUS_ROUTES_REQUEST,
  ADD_BUS_ROUTE_REQUEST,
  ADD_BUS_ROUTE_SUCCESS,
  UPDATE_BUS_ROUTE_REQUEST,
  UPDATE_BUS_ROUTE_SUCCESS,
  SET_ACTIVE_BUS_ROUTE,
  CLEAR_ACTIVE_BUS_ROUTE,
};
