const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
const GET_LIST_POSTS_SUCCESS = 'GET_LIST_POSTS_SUCCESS';
const GET_LIST_POSTS_REQUEST = 'GET_LIST_POSTS_REQUEST';
const ADD_POST_REQUEST = 'ADD_POST_REQUEST';
const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
const UPDATE_POST_REQUEST = 'UPDATE_POST_REQUEST';
const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
const SET_ACTIVE_POST = 'SET_ACTIVE_POST';
const CLEAR_ACTIVE_POST = 'CLEAR_ACTIVE_POST';

export const postTypes = {
  DELETE_POST_SUCCESS,
  DELETE_POST_REQUEST,
  GET_LIST_POSTS_SUCCESS,
  GET_LIST_POSTS_REQUEST,
  ADD_POST_REQUEST,
  ADD_POST_SUCCESS,
  UPDATE_POST_REQUEST,
  UPDATE_POST_SUCCESS,
  SET_ACTIVE_POST,
  CLEAR_ACTIVE_POST,
};
