const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
const GET_LIST_USERS_SUCCESS = 'GET_LIST_USERS_SUCCESS';
const GET_LIST_USERS_REQUEST = 'GET_LIST_USERS_REQUEST';
const ADD_USER_REQUEST = 'ADD_USER_REQUEST';
const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
const SET_ACTIVE_USER = 'SET_ACTIVE_USER';
const CLEAR_ACTIVE_USER = 'CLEAR_ACTIVE_USER';
const ADD_BUS_ROUTE_TO_FAVOURITES = 'ADD_BUS_ROUTE_TO_FAVOURITES';
const REMOVE_BUS_ROUTE_FROM_FAVOURITES = 'REMOVE_BUS_ROUTE_FROM_FAVOURITES';

export const userTypes = {
  DELETE_USER_SUCCESS,
  DELETE_USER_REQUEST,
  GET_LIST_USERS_SUCCESS,
  GET_LIST_USERS_REQUEST,
  ADD_USER_REQUEST,
  ADD_USER_SUCCESS,
  UPDATE_USER_REQUEST,
  UPDATE_USER_SUCCESS,
  SET_ACTIVE_USER,
  CLEAR_ACTIVE_USER,
  ADD_BUS_ROUTE_TO_FAVOURITES,
  REMOVE_BUS_ROUTE_FROM_FAVOURITES
};
